sonar.projectKey=technova-inventory
sonar.projectName=TechNova Inventory Service
sonar.projectVersion=1.0.0

sonar.sources=app
sonar.tests=app/tests
sonar.exclusions=app/tests/**

sonar.python.version=3.10
sonar.sourceEncoding=UTF-8